name: Hugo Build and Deploy

on:
  push:
    branches:
      - main  # 仅在 main 分支推送时触发该工作流

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.139.4'  # 指定 Hugo 版本，确保和项目兼容

      # Step 3: 生成静态文件
      - name: Build
        run: hugo --minify  # Hugo 构建站点，生成到 public/ 目录

      # Step 4: 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub Pages 授权
          publish_dir: ./public                     # Hugo 输出的目录
          publish_branch: gh-pages                  # 部署的目标分支
